version: '2.2'
services:
    vufind:
        image: "moravianlibrary/${IMAGE_NAME:-cpk-deploy}:${IMAGE_VERSION:-latest}"
        extends:
            file: docker-compose.yaml
            service: cpk
        env_file:
           - deploy.env
        build:
            context: "builds/cpk-source"
            args:
                PARAM_VUFIND_BRANCH: ""
                PARAM_VUFIND_COMMIT_HASH: ""
        network_mode: bridge
